/*
 * CS103AboutDialog.java
 *
 * Created on November 4, 2008, 11:32 AM
 */
package cs103.gui;

import chs103.physical.BareBonesBrowserLaunch;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.ResourceBundle;
import javax.imageio.ImageIO;

/**
 *
 * @author user
 */
public class CS103AboutDialog extends java.awt.Dialog {

    private String FILENAME = "config/program.properties";
    private static final ResourceBundle bundle = java.util.ResourceBundle.getBundle("resource/CS103AboutDialog"); // NOI18N

    /**
     * Creates new form CS103AboutDialog
     */
    public CS103AboutDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationToCenter();
        this.setTitle(bundle.getString("CS103AboutDialog.Title.text"));
        BufferedImage image = null;
        try {
            image = ImageIO.read(this.getClass().getResource("cs103_win_icon.gif"));
            this.setIconImage(image);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buildTextArea = new javax.swing.JTextArea();
        contentTextArea = new javax.swing.JTextArea();
        versionTextArea = new javax.swing.JTextArea();
        programTextArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        websiteButton = new javax.swing.JButton();
        mailButton = new javax.swing.JButton();
        lblRevision = new javax.swing.JLabel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setMaximumSize(new java.awt.Dimension(400, 280));
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 280));

        buildTextArea.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        buildTextArea.setColumns(20);
        buildTextArea.setEditable(false);
        buildTextArea.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        buildTextArea.setRows(5);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("resource/CS103AboutDialog"); // NOI18N
        buildTextArea.setText(bundle.getString("CS103AboutDialog.buildTextArea.text")); // NOI18N
        buildTextArea.setWrapStyleWord(true);

        contentTextArea.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        contentTextArea.setColumns(20);
        contentTextArea.setEditable(false);
        contentTextArea.setFont(new java.awt.Font("Courier New", 0, 12));
        contentTextArea.setRows(5);
        contentTextArea.setText(bundle.getString("CS103AboutDialog.contentTextArea.text")); // NOI18N

        versionTextArea.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        versionTextArea.setColumns(20);
        versionTextArea.setEditable(false);
        versionTextArea.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        versionTextArea.setRows(5);
        versionTextArea.setText(bundle.getString("CS103AboutDialog.versionTextArea.text")); // NOI18N

        programTextArea.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        programTextArea.setColumns(20);
        programTextArea.setEditable(false);
        programTextArea.setFont(new java.awt.Font("Arial", 0, 18));
        programTextArea.setRows(5);
        programTextArea.setText(bundle.getString("CS103AboutDialog.programTextArea.text")); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cs103/gui/cs103_about_icon.GIF"))); // NOI18N

        websiteButton.setFont(new java.awt.Font("Tahoma", 1, 11));
        websiteButton.setForeground(new java.awt.Color(0, 0, 204));
        websiteButton.setText("http://www.agrologic.com");
        websiteButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        websiteButton.setBorderPainted(false);
        websiteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                websiteButtonActionPerformed(evt);
            }
        });

        mailButton.setFont(new java.awt.Font("Tahoma", 1, 11));
        mailButton.setForeground(new java.awt.Color(0, 0, 204));
        mailButton.setText("info@agrologic.com");
        mailButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        mailButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mailButtonActionPerformed(evt);
            }
        });

        lblRevision.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        lblRevision.setText("Revision : 25.06.2012 ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jLabel1)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(programTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(versionTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buildTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRevision)))
            .addComponent(contentTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(websiteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(mailButton, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(programTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(versionTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(buildTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblRevision)))
                .addGap(15, 15, 15)
                .addComponent(contentTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(websiteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(mailButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        versionTextArea.getAccessibleContext().setAccessibleParent(jPanel1);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Moves this component to a center of screen.
     *
     * @see #setLocation
     * @see #setBounds
     */
    public void setLocationToCenter() {
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int x = screenSize.width / 2 - this.getWidth() / 2;
        int y = screenSize.height / 2 - this.getHeight() / 2;
        this.setLocation(x, y);
    }

    /**
     * Set version .
     */
    public void setVersionInTitle(String vers) {
        String title = getTitle() + " V" + vers;
        setTitle(title);
    }

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

private void websiteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_websiteButtonActionPerformed
    BareBonesBrowserLaunch.openURL(websiteButton.getText().trim());
}//GEN-LAST:event_websiteButtonActionPerformed

private void mailButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mailButtonActionPerformed
    try {
        //try statement
        Runtime.getRuntime().exec("cmd /c start mailto:info@agrologic.com");   //open the file

    } catch (Exception ex) {                  //catch any exceptions here
        System.out.println("Error" + ex);  //print the error
    }
}//GEN-LAST:event_mailButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                CS103AboutDialog dialog = new CS103AboutDialog(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea buildTextArea;
    private javax.swing.JTextArea contentTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblRevision;
    private javax.swing.JButton mailButton;
    private javax.swing.JTextArea programTextArea;
    private javax.swing.JTextArea versionTextArea;
    private javax.swing.JButton websiteButton;
    // End of variables declaration//GEN-END:variables
}
