/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CS103SettingDialog.java
 *
 * Created on Aug 28, 2011, 10:17:47 AM
 */
package cs103.gui;

import chs103.physical.PropertyFileManager;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.Locale;
import java.util.ResourceBundle;

/**
 *
 * @author valery
 */
public class CS103SettingDialog extends javax.swing.JDialog {

    /**
     * Creates new form CS103SettingDialog
     */
    public CS103SettingDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Windows.centerOnScreen(this);
        String weightunit = PropertyFileManager.getProperty(CS103App.FILENAME, "weightunit");
        if (weightunit.equals("gram")) {
            btnGroupWeight.setSelected(rdoGram.getModel(), true);
            btnGroupWeight.setSelected(rdoPound.getModel(), false);
        } else if (weightunit.equals("pound")) {
            btnGroupWeight.setSelected(rdoGram.getModel(), false);
            btnGroupWeight.setSelected(rdoPound.getModel(), true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupWeight = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        rdoPound = new javax.swing.JRadioButton();
        rdoGram = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("resource/CS103SettingDialog"); // NOI18N
        setTitle(bundle.getString("CS103SettingDialog.Title.text")); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("CS103SettingDialog.Panel.Units.text"))); // NOI18N

        btnGroupWeight.add(rdoPound);
        rdoPound.setText(bundle.getString("CS103SettingDialog.Radio.Pound.text")); // NOI18N
        rdoPound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoPoundActionPerformed(evt);
            }
        });

        btnGroupWeight.add(rdoGram);
        rdoGram.setText(bundle.getString("CS103SettingDialog.Radio.Gram.text")); // NOI18N
        rdoGram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoGramActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdoPound)
                    .addComponent(rdoGram))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rdoPound)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdoGram)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdoGramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoGramActionPerformed
        setCurrentWeight(CS103App.WeightUnit.gram);
    }//GEN-LAST:event_rdoGramActionPerformed

    private void rdoPoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoPoundActionPerformed
        setCurrentWeight(CS103App.WeightUnit.pound);
    }//GEN-LAST:event_rdoPoundActionPerformed

    private void setCurrentWeight(CS103App.WeightUnit unit) {
        if (unit == CS103App.WeightUnit.gram) {
            PropertyFileManager.setProperty(CS103App.FILENAME, "", "weightunit", "gram");
        } else if (unit == CS103App.WeightUnit.pound) {
            PropertyFileManager.setProperty(CS103App.FILENAME, "", "weightunit", "pound");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                CS103SettingDialog dialog = new CS103SettingDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroupWeight;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rdoGram;
    private javax.swing.JRadioButton rdoPound;
    // End of variables declaration//GEN-END:variables
}
